services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: shiny
    image: naturecons/sitesdata
    ports:
      - "3838:3838"
    environment:
      - R_CONFIG_ACTIVE
      - WORK_DIR=${PWD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRANSACTION_DB}:/opt/db
