services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: shiny
    image: naturecons/sitesdata
    ports:
      - "3838:3838"
    environment:
      # environmental variables defined in ./.env
      - R_CONFIG_ACTIVE
